version: '3.3'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html/wordpress
    networks:
      - front
    env_file:
      - .env
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
    - ./data/wordpress:/var/www/html/wordpress
      # - wordpress:/var/www/html/wordpress
    networks:
      - front
    env_file:
      - .env
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - ./data/wordpress:/var/lib/mysql
    networks:
      - front
    env_file:
      - .env
    restart: always
networks:
  front:
    driver: bridge
# volumes:
#   mariadb_data:
#     driver: local
#     driver_opts:
#       device: /Users/hkahsay/data/mariadb
#       type: volume
#       o: bind
#   wordpress_data:
#     driver: local
#     driver_opts:
#       device: /Users/hkahsay/data/wordpress
#       type: volume
#       o: bind
volumes:
  wordpress:
  mariadb:
# networks:
#   front:
