version: '3.3'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    # depends_on:
      # - wordpress
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html/wordpress
    networks:
      - front
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    # volumes:
    #   - ./data/wordpress:/var/www/html/wordpress
    networks:
      - front
    env_file:
      - .env
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    # volumes:
    #   - ./data/mariadb:/var/lib/mysql
    networks:
      - front
    restart: always
volumes:
  wordpress:
  mariadb:
networks:
  front:
